apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: trading-api
  namespace: trading
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc-trading-api
  service:
    port: 8080
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 5
    metrics:
      - name: request-success-rate
        thresholdRange: { min: 99 }
        interval: 1m
      - name: request-duration
        thresholdRange: { max: 500 }
        interval: 1m
