apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: trading-api-deny-by-default
  namespace: trading
spec:
  podSelector:
    matchLabels: { app: svc-trading-api }
  policyTypes: ["Ingress","Egress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gateway
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 15090
